### ISSUE TITLE
RSS feed is invalid when a category contains illegal characters

### ISSUE THREAD

**Issue by EdwinVW** [wmeints/hexo-generator-feed-per-category#1] opened 2016-06-03 06:41 UTC
When a category contains an illegal character (ampersand '&' or whitespace??), the feed breaks. See: [http://defaultconstructor.com/atom.xml](http://defaultconstructor.com/atom.xml)

**Comment by wmeints** [comment] 2016-06-03 12:30
Thanks for reporting this. Will try to reproduce this and make a fix for the problem.

**Comment by wmeints** [comment] 2016-06-12 09:35
Hi Edwin,

I spend some time trying to reproduce your problem and I think it's actually not in the category feed plugin. The `hexo-generator-feed` plugin seems to cause the problems. They removed all their escape code from the Atom feed template in March and that causes problems for me.

Could you check your category feed and see if that feed renders correctly?

**Comment by wmeints** [comment] 2016-06-23 18:49
I'm going to close this, since the error is in the general feed not in the category feeds.

**Closed by wmeints** 2016-06-23 18:49 UTC
Labels: bug, waiting for response
